//4. Faca uma funcao para verificar se um numero e um quadrado perfeito. Um quadrado 
//perfeito e um numero inteiro nao negativo que pode ser expresso como o quadrado de 
///outro numero inteiro. Ex: 1, 4, 9... 